#!/bin/bash

last=$(ls out -Art | tail -1)
batch=$(ls out/$last -Art | tail -1)

echo $(ls out)
echo "$last -> $(ls out/$last)"
echo grep on out/$last/$batch
cat out/$last/$batch/mandelbrot.c | grep "# pragma"
