#!/bin/bash

last=$(ls out -Art | tail -1)
batch=$(ls out/$last/ -Art | tail -2 | xargs -n1 | grep BATCH*)

echo $(ls out)
echo "$last -> $(ls out/$last)"
echo grep on out/$last/$batch
watch cat out/$last/*.out out/$last/$batch/output out/$last/$batch/tempo
