#!/bin/bash

#SBATCH --export=ALL
#SBATCH --ntasks 32
#SBATCH --nodes 4
#SBATCH --ntasks-per-node=16

#SBATCH -t 60

#SBATCH --exclusive

#SBATCH --mail-type=ALL
#SBATCH --mail-user=example@edu.pucrs.br

#SBATCH --no-requeue
#SBATCH -o %x.%j.out

#SBATCH -D /home/pptm02/t1

################
echo Running on host `hostname`
echo
echo Initial Time is `date`
echo
echo Directory is `pwd`
echo
echo This jobs runs on the following nodes:
echo $SLURM_JOB_NODELIST
echo
echo JOB_ID:
echo $SLURM_JOBID
echo ################

############# Commands...

folder=$(ls out -Art | tail -1)
echo Running on folder: $folder

mkdir out/$folder/BATCH_$SLURM_JOBID

cp pptm.cpp ./out/$folder/BATCH_$SLURM_JOBID
touch out/$folder/BATCH_$SLURM_JOBID/4_NODOS

./job out/$folder/BATCH_$SLURM_JOBID 16
